### ISSUE TITLE
FileNotFoundError: No such file: '/home/sys006/ChatSim/results/cache/1137_demo_2024_12_04_18_49_56/blender_output/0/RGB_composite.png'  &  OSError: load: data/blender_assets/Benz_G.blend failed to open blend file

### ISSUE THREAD

**Issue by obk0515** [yifanlu0227/ChatSim#56]
When I run `python main.py -y config/3dgs-waymo-1137.yaml -p "Add a Benz G in front of me, driving away fast."`. I meet this error.
```
[User prompt] Add a Benz G in front of me, driving away fast.

[Project Manager] decomposing tasks                
[Raw Response>>>] { 1: 'Add a Benz G in front of the viewpoint, driving away fast' }
[Extracted Response>>>] { 1: 'Add a Benz G in front of the viewpoint, driving away fast' } 

[Performing Single Prompt] Add a Benz G in front of the viewpoint, driving away fast

[Project Manager] dispatching each task                 
[Raw Response>>>] {'operation': 1}
[Extracted Response>>>] 1. (adding) 

[Motion Agent LLM] analyzing insertion scene dependency                      
[Raw Response>>>] {'dependency': 0}
[Extracted Response>>>] {'dependency': 0} 

[Motion Agent LLM] deciding scene-independent object placement                     
[Raw Response>>>] {'mode':'front', 'distance_constraint': 0, 'distance_min_max':(4, 45)}
[Extracted Response>>>] {'mode': 'front', 'distance_constraint': 0, 'distance_min_max': (4, 45)} 

[Asset Agent LLM] deciding asset type and color                     
[Raw Response>>>] {'color':'default', 'type':'benz_g'}
[Extracted Response>>>] {'color': 'default', 'type': 'benz_g'} 

[Motion Agent LLM] finding motion prior                     
[Raw Response>>>] {'action': 'straight', 'speed': 'fast', 'direction': 'away', 'wrong_way': 'false'}
[Extracted Response>>>] {'action': 'straight', 'speed': 'fast', 'direction': 'away', 'wrong_way': 'false'} 

scene.added_cars_dict dict_keys(['added_car_0'])
scene.removed_cars []
[Background Gaussian Splatting] is_ego_motion is False, rendering one frame
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
	Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
camera_extrinsics: (1, 3, 4)
camera_intrinsics: (3, 3)
H: 1280, W: 5760
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.85it/s]
Rendering and saving to images [04/12 18:50:10]
1it [00:00,  1.89it/s]
[Inpaint] No inpainting.
[Blender] Start rendering 15 images.
see the log in results/cache/1137_demo_2024_12_04_18_49_56/rendering_log if save_cache is enabled
preparing input files for blender rendering
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 62.61it/s]
start rendering in parallel, process number is 1.
This may take a few minutes. To speed up the foreground rendering, you can lower the `frames` number or render not-wide images.
If you find the results are incomplete or missing, that may due to OOM. You can reduce the multi_process_num in config yaml.
You can also check the log file for debugging with `save_cache` enabled in the yaml.
[Blender] Finish rendering 15 images.
[Blender] Copying Remaining 0 images.
Traceback (most recent call last):
  File "/home/sys006/ChatSim/main.py", line 142, in <module>
    chatsim.execute_funcs()
  File "/home/sys006/ChatSim/main.py", line 127, in execute_funcs
    self.foreground_rendering_agent.func_blender_add_cars(self.scene)
  File "/home/sys006/ChatSim/chatsim/agents/foreground_rendering_agent.py", line 120, in func_blender_add_cars
    img = imageio.imread(video_frame_file)
  File "/home/sys006/anaconda3/envs/chatsim/lib/python3.9/site-packages/imageio/v2.py", line 359, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/home/sys006/anaconda3/envs/chatsim/lib/python3.9/site-packages/imageio/core/imopen.py", line 113, in imopen
    request = Request(uri, io_mode, format_hint=format_hint, extension=extension)
  File "/home/sys006/anaconda3/envs/chatsim/lib/python3.9/site-packages/imageio/core/request.py", line 247, in __init__
    self._parse_uri(uri)
  File "/home/sys006/anaconda3/envs/chatsim/lib/python3.9/site-packages/imageio/core/request.py", line 407, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/home/sys006/ChatSim/results/cache/1137_demo_2024_12_04_18_49_56/blender_output/0/RGB_composite.png'
```

Then I check `1137_demo_2024_12_04_18_49_56/rendering_log/0.txt`:
```
Blender 3.5.1 (hash e1ccd9d4a1d3 built 2023-04-24 23:31:15)
Warning: Unable to open 'data/blender_assets/Benz_G.blend': No such file or directory
Error: Python: Traceback (most recent call last):
  File "/home/sys006/ChatSim/chatsim/foreground/Blender/utils/blender_utils/main_multicar.py", line 95, in <module>
    main()
  File "/home/sys006/ChatSim/chatsim/foreground/Blender/utils/blender_utils/main_multicar.py", line 92, in main
    render(render_opt)
  File "/home/sys006/ChatSim/chatsim/foreground/Blender/utils/blender_utils/main_multicar.py", line 31, in render
    add_model_params(car_obj)
  File "/home/sys006/ChatSim/chatsim/foreground/Blender/utils/blender_utils/model/set_model.py", line 76, in add_model_params
    with bpy.data.libraries.load(blender_file, link=False) as (data_from, data_to):
OSError: load: data/blender_assets/Benz_G.blend failed to open blend file

Blender quit
```

How can I deal with this error.Thank you very much.

**Comment by obk0515** [comment]
I solved this error.
The correct path is `data/blender_assets/assets/Benz_G.blend`
So we need to modify it in the `config/***.yaml`.
